spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: postgres
    password: "%Nw8Fm1qc*HXFh3mK}|9GOzATC}8LQrh"

book-service:
  base-url: http://localhost:8080/books
  secret-key: "4Ai+5X3ZuK4J+T44sp0RDL48WeieeIq0boPRJb89MMU="