spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

book-service:
  base-url: ${BOOK_SERVICE_BASE_URL}
  secret-key: ${BOOK_SERVICE_SECRET_API_KEY}